In [1]:
import pandas as pd

In [2]:
df_company = pd.read_csv("../Data/ai_company_adoption.csv")

In [3]:
df_company.head()

,response_id,company_id,survey_year,quarter,country,region,industry,company_size,num_employees,annual_revenue_usd_millions,...,productivity_change_percent,jobs_displaced,jobs_created,reskilled_employees,revenue_growth_percent,cost_reduction_percent,innovation_score,customer_satisfaction,survey_source,data_collection_method
0,1,COMP-00001,2023,Q1,Italy,Europe,Education,Startup,57,48.31,...,2.65,1,1,3,2.52,9.45,53,5.20,WEF Survey,API Scrape
1,2,COMP-00001,2023,Q2,Italy,Europe,Education,Startup,57,48.31,...,5.77,2,2,5,4.77,0.00,51,6.98,McKinsey Report,Phone Interview
2,3,COMP-00001,2023,Q3,Italy,Europe,Education,Startup,57,48.31,...,6.94,3,3,2,12.87,9.74,40,4.12,Internal Corporate Survey,Research Compilation
3,4,COMP-00001,2023,Q4,Italy,Europe,Education,Startup,57,48.31,...,5.32,1,1,2,8.19,0.00,51,5.72,Internal Corporate Survey,Research Compilation
4,5,COMP-00001,2024,Q1,Italy,Europe,Education,Startup,57,48.31,...,6.32,2,3,6,11.30,9.02,43,6.31,McKinsey Report,Research Compilation

In [4]:
df_company.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 43 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   response_id                  150000 non-null  int64
 1   company_id                   150000 non-null  object
 2   survey_year                  150000 non-null  int64
 3   quarter                      150000 non-null  object
 4   country                      150000 non-null  object
 5   region                       150000 non-null  object
 6   industry                     150000 non-null  object
 7   company_size                 150000 non-null  object
 8   num_employees                150000 non-null  int64
 9   annual_revenue_usd_millions  150000 non-null  float64
 10  company_founding_year        150000 non-null  int64
 11  company_age                  150000 non-null  int64
 12  company_age_group            150000 non-null  object
 13  ai_adoption_rate             150000 non-null  float64
 14  ai_adoption_stage            150000 non-null  object
 15  years_using_ai               150000 non-null  int64
 16  ai_primary_tool              150000 non-null  object
 17  num_ai_tools_used            150000 non-null  int64
 18  ai_use_case                  150000 non-null  object
 19  ai_projects_active           150000 non-null  int64
 20  ai_training_hours            150000 non-null  float64
 21  ai_budget_percentage         150000 non-null  float64
 22  ai_maturity_score            150000 non-null  float64
 23  ai_failure_rate              150000 non-null  float64
 24  ai_investment_per_employee   150000 non-null  float64
 25  regulatory_compliance_score  150000 non-null  int64
 26  data_privacy_level           150000 non-null  object
 27  ai_ethics_committee          150000 non-null  object
 28  ai_risk_management_score     150000 non-null  int64
 29  remote_work_percentage       150000 non-null  float64
 30  employee_satisfaction_score  150000 non-null  float64
 31  task_automation_rate         150000 non-null  float64
 32  time_saved_per_week          150000 non-null  float64
 33  productivity_change_percent  150000 non-null  float64
 34  jobs_displaced               150000 non-null  int64
 35  jobs_created                 150000 non-null  int64
 36  reskilled_employees          150000 non-null  int64
 37  revenue_growth_percent       150000 non-null  float64
 38  cost_reduction_percent       150000 non-null  float64
 39  innovation_score             150000 non-null  int64
 40  customer_satisfaction        150000 non-null  float64
 41  survey_source                150000 non-null  object
 42  data_collection_method       150000 non-null  object
dtypes: float64(15), int64(14), object(14)
memory usage: 49.2+ MB

In [5]:
df_company.isnull().sum()

response_id                    0
company_id                     0
survey_year                    0
quarter                        0
country                        0
region                         0
industry                       0
company_size                   0
num_employees                  0
annual_revenue_usd_millions    0
company_founding_year          0
company_age                    0
company_age_group              0
ai_adoption_rate               0
ai_adoption_stage              0
years_using_ai                 0
ai_primary_tool                0
num_ai_tools_used              0
ai_use_case                    0
ai_projects_active             0
ai_training_hours              0
ai_budget_percentage           0
ai_maturity_score              0
ai_failure_rate                0
ai_investment_per_employee     0
regulatory_compliance_score    0
data_privacy_level             0
ai_ethics_committee            0
ai_risk_management_score       0
remote_work_percentage         0
employee_satisfaction_score    0
task_automation_rate           0
time_saved_per_week            0
productivity_change_percent    0
jobs_displaced                 0
jobs_created                   0
reskilled_employees            0
revenue_growth_percent         0
cost_reduction_percent         0
innovation_score               0
customer_satisfaction          0
survey_source                  0
data_collection_method         0
dtype: int64

In [6]:
df_company.duplicated().sum()

np.int64(0)

In [7]:
df_company.describe()

,response_id,survey_year,num_employees,annual_revenue_usd_millions,company_founding_year,company_age,ai_adoption_rate,years_using_ai,num_ai_tools_used,ai_projects_active,...,task_automation_rate,time_saved_per_week,productivity_change_percent,jobs_displaced,jobs_created,reskilled_employees,revenue_growth_percent,cost_reduction_percent,innovation_score,customer_satisfaction
count,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,...,150000.000000,150000.000000,150000.000000,150000.00000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000
mean,79961.106207,2024.500987,2342.376580,1180.345751,2005.993767,18.507220,36.414726,4.931580,2.315120,6.270693,...,19.761744,6.267406,9.266996,111.36984,117.882507,181.642700,4.606486,4.814909,55.199920,5.420619
std,46158.813039,1.118013,4754.424755,2391.471420,9.473220,9.539367,14.544096,2.429316,0.946826,3.500142,...,9.222562,2.977495,5.637067,255.83778,261.650245,417.929587,5.318773,3.383086,8.593423,1.047142
min,1.000000,2023.000000,10.000000,1.010000,1990.000000,1.000000,0.000000,0.000000,1.000000,0.000000,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,-5.000000,0.000000,40.000000,1.000000
25%,40020.750000,2024.000000,69.000000,33.880000,1998.000000,10.000000,26.430000,3.000000,2.000000,4.000000,...,13.360000,4.180000,5.070000,2.00000,3.000000,3.000000,0.780000,2.120000,49.000000,4.700000
50%,79937.500000,2025.000000,349.000000,184.160000,2006.000000,18.000000,36.320000,5.000000,2.000000,6.000000,...,19.700000,6.230000,9.060000,10.00000,12.000000,16.000000,4.480000,4.620000,55.000000,5.410000
75%,119913.250000,2026.000000,884.000000,444.150000,2014.000000,27.000000,46.200000,7.000000,3.000000,9.000000,...,26.020000,8.290000,13.120000,41.00000,41.000000,64.000000,8.240000,7.130000,61.000000,6.130000
max,160000.000000,2026.000000,19970.000000,9996.730000,2022.000000,36.000000,100.000000,10.000000,6.000000,20.000000,...,59.630000,19.150000,34.360000,2417.00000,1980.000000,3881.000000,30.000000,20.790000,97.000000,9.760000

In [8]:
df_company.describe(include = 'object')

,company_id,quarter,country,region,industry,company_size,company_age_group,ai_adoption_stage,ai_primary_tool,ai_use_case,data_privacy_level,ai_ethics_committee,survey_source,data_collection_method
count,150000,150000,150000,150000,150000,150000,150000,150000,150000,150000,150000,150000,150000,150000
unique,10000,4,30,6,9,3,4,4,6,8,3,2,4,4
top,COMP-09978,Q4,France,Asia,Technology,SME,16-30 years,partial,ChatGPT,Customer Support,High,No,LinkedIn Poll,Research Compilation
freq,16,37542,5637,49727,21107,63867,68383,78800,46103,37683,64922,88479,37727,37650

In [9]:
df_company[['ai_adoption_rate', 'annual_revenue_usd_millions', 'productivity_change_percent']].corr()

,ai_adoption_rate,annual_revenue_usd_millions,productivity_change_percent
ai_adoption_rate,1.000000,0.191219,0.674973
annual_revenue_usd_millions,0.191219,1.000000,0.215749
productivity_change_percent,0.674973,0.215749,1.000000

In [10]:
df_company['rev_per_employee'] = df_company['annual_revenue_usd_millions'] / df_company['num_employees']

In [11]:
df_company[['industry', 'rev_per_employee']].sort_values(by='rev_per_employee', ascending=False).head()

         industry  rev_per_employee
124964  Education          9.456657
124963  Education          9.456657
124955  Education          9.456657
124956  Education          9.456657
124957  Education          9.456657

In [12]:
# 1. List the columns we want to keep
golden_columns = [
    'company_id', 'country', 'region', 'industry', 'company_size', 
    'annual_revenue_usd_millions', 'num_employees', 'rev_per_employee',
    'ai_adoption_rate', 'ai_adoption_stage', 'productivity_change_percent',
    'survey_year', 'quarter'
]

# 2. Create a final dataframe with ONLY these columns
df_final = df_company[golden_columns]

# 3. EXPORT! This saves the file to your 'outputs' folder
df_final.to_csv('../outputs/AI_Adoption_Final_Clean.csv', index=False)

print("Success! Your cleaned file is ready in the outputs folder.")

Success! Your cleaned file is ready in the outputs folder.